kind: Service
apiVersion: v1
metadata:
  name: keycloak-user-service
  namespace: fips-test
  labels:
    app: keycloak-user-service
  annotations:
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1680726530
    service.beta.openshift.io/serving-cert-secret-name: keycloak-user-service
    service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1680726530
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: keycloak-user-service
status:
  loadBalancer: {}
